# Generated by Django 4.2.16 on 2025-05-31 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_post_shared_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('haha', '😄'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠')], default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('haha', '😄'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠')], default='like', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('created_by', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('created_by', 'post')},
        ),
    ]
