# Generated by Django 4.2.16 on 2025-06-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_commentlike_reaction_type_like_reaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('haha', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😡')], default='like', max_length=10),
        ),
        migrations.AlterField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('haha', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😡')], default='like', max_length=10),
        ),
    ]
