# Generated by Django 4.2.16 on 2025-06-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_groupinvitation_unique_together'),
        ('posts', '0006_alter_commentlike_reaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='group.group'),
        ),
    ]
