# Generated by Django 4.2.16 on 2025-06-04 10:21

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_covers/', validators=[posts.models.validate_svg_or_image]),
        ),
    ]
