# Generated by Django 4.2.16 on 2025-06-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_cover_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvitation',
            unique_together=set(),
        ),
    ]
