# Generated by Django 4.2.16 on 2025-06-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_commentlike_reaction_type_and_more'),
        ('accounts', '0005_user_saved_posts_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='posts.post'),
        ),
    ]
