# Generated by Django 4.2.16 on 2025-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('comment_like', 'Comment Like'), ('friend_request', 'Friend Request'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_rejected', 'Friend Request Rejected'), ('friend_request_cancelled', 'Friend Request Cancelled'), ('group_invitation', 'Group Invitation'), ('group_invitation_accepted', 'Group Invitation Accepted'), ('group_invitation_declined', 'Group Invitation Declined'), ('group_member_removed', 'Group Member Removed')], max_length=50),
        ),
    ]
